# .github/workflows/test.yml
name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    environment: AIRTABLE_API_KEY
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm test -- --ci --reporters=default --reporters=jest-junit
      - name: update Airtable
        if: always ()
        run: node ./.scripts/airtableScript.js ${{secrets.AIRTABLE_API_KEY}} ${{secrets.AIRTABLE_BASE_ID}} ${{secrets.AIRTABLE_TABLE_NAME}} ${{secrets.AIRTABLE_STUDENTS_TABLE_NAME}}  ${{github.actor}} https://github.com/${{github.repository}}
